facebook:
  label: Facebook
  permalink: /facebook
  description: Facebook tag description

hello:
  label: Hello
  permalink: /hello
  description: Hello tag description

docusaurus:
  label: Docusaurus
  permalink: /docusaurus
  description: Docusaurus tag description

hola:
  label: Hola
  permalink: /hola
  description: Hola tag description

github-actions:
  label: GitHub Actions
  description: Automate workflows using GitHub Actions.

automation:
  label: Automation
  description: Automating processes to improve efficiency.

release-management:
  label: Release Management
  description: Strategies and tools for managing software releases.